=== tiernan/jay-walker/schemas/levels.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
	"name": {
	  "description": "Name used for level in game",
	  "type": "string"
	},
	"origin": {
	  "description": "Starting position of player",
	  "type": "array",
	  "items": {
		"description": "Coordinate of player (x, then y)",
		"type": "integer"
	  },
	  "minItems": 2,
	  "maxItems": 2
	},
	"layout": {
	  "description": "Array of level rows and enemies",
	  "type": "array",
	  "items": {
		"description": "Level row object",
		"type": "object",
		"properties": {
		  "material": {
			"description": "Material to paint as background",
			"type": "string"
		  },
		  "reverse": {
			"description": "Do enemies move in reverse on this row",
			"type": "boolean"
		  },
		  "speed": {
			"description": "Speed multiplier of enemies on this row",
			"type": "number"
		  },
		  "enemies": {
			"description": "Array of enemy entities on this row",
			"type": "array",
			"items": {
			  "description": "Enemy object",
			  "type": "object",
			  "properties": {
				"delay": {
				  "description": "How many ticks before enemy appears",
				  "type": "number"
				},
				"mode": {
				  "description": "Entity mode to be passed to constructor",
				  "type": "number"
				},
				"type": {
				  "description": "Array of entities to use for this row",
				  "type": "array",
				  "items": {
					"description": "Entity class name",
					"type": "string"
				  },
				  "minItems": 1,
				  "uniqueItems": true
				}
			  },
			  "required": [
				"delay",
				"type"
			  ]
			},
			"minItems": 1
		  }
		},
		"required": [
		  "material"
		]
	  }
	},
	"startFrame": {
	  "description": "Ticks to skip before start",
	  "type": "integer"
	}
  },
  "required": [
	"name",
	"origin",
	"layout",
	"startFrame"
  ]
}

=== tiernan/jay-walker/dist/data/levels/tx2.json
{"name":"Level 2","origin":[5,5],"layout":[{"material":"images/stone-block.png"},{"material":"images/stone-block.png","reverse":true,"speed":1.8,"enemies":[{"delay":4,"type":["SportsCar","MuscleCar"]},{"delay":8,"type":["SportsCar","ClassicCar"]},{"delay":10,"type":["Taxi","MuscleCar","ClassicCar"]}]},{"material":"images/grass-block.png","reverse":true,"speed":1.4,"enemies":[{"delay":1,"type":["Bug"]},{"delay":5,"type":["Bug"]},{"delay":8,"type":["Bug"]}]},{"material":"images/stone-block.png","speed":2,"enemies":[{"delay":3,"type":["Police"]},{"delay":5,"type":["Police"]},{"delay":8,"type":["Truck","Van","Pickup"]}]},{"material":"images/stone-block.png","speed":2.6,"enemies":[{"delay":1,"mode":1,"type":["SportsCar"]},{"delay":4,"mode":1,"type":["Police"]}]},{"material":"images/grass-block.png"}],"startFrame":3}

=== tiernan/jay-walker/dist/data/levels/tx1.json
{"name":"Level 1","origin":[5,5],"layout":[{"material":"images/grass-block.png"},{"material":"images/stone-block.png","reverse":true,"speed":1.2,"enemies":[{"delay":1,"type":["ClassicCar","Taxi","MuscleCar","Van","Pickup"]},{"delay":8,"type":["SportsCar"]},{"delay":4,"type":["ClassicCar","Taxi","MuscleCar","Van"]}]},{"material":"images/stone-block.png","speed":2,"enemies":[{"delay":1,"type":["ClassicCar","Taxi","Van"]},{"delay":3,"type":["Taxi","Truck","Van","Pickup"]},{"delay":7,"type":["MuscleCar","Taxi","Truck","Van"]}]},{"material":"images/stone-block.png","speed":2,"enemies":[{"delay":3,"type":["Police"]},{"delay":6,"type":["Police"]}]},{"material":"images/grass-block.png","speed":1.4,"enemies":[{"delay":1,"type":["Bug"]},{"delay":4,"type":["Bug"]},{"delay":6,"type":["Bug"]},{"delay":9,"type":["Bug"]}]},{"material":"images/grass-block.png"}],"startFrame":4}

=== tiernan/jay-walker/dist/data/levels/tx3.json
{"name":"Level 3","origin":[5,5],"layout":[{"material":"images/water-block.png"},{"material":"images/stone-block.png","reverse":true,"speed":3,"enemies":[{"delay":1,"mode":1,"type":["SportsCar"]},{"delay":4,"mode":1,"type":["Police"]},{"delay":6,"mode":1,"type":["Police"]},{"delay":8,"mode":1,"type":["Police"]}]},{"material":"images/stone-block.png","reverse":true,"speed":1.6,"enemies":[{"delay":1,"type":["ClassicCar","Taxi","MuscleCar","Van","Pickup"]},{"delay":4,"type":["Truck","Van","Pickup"]},{"delay":8,"type":["ClassicCar","Taxi","MuscleCar","Van"]}]},{"material":"images/stone-block.png","speed":2,"enemies":[{"delay":3,"type":["Police"]},{"delay":5,"type":["Police"]},{"delay":8,"type":["Truck","Van","Pickup"]}]},{"material":"images/stone-block.png","speed":2.6,"enemies":[{"delay":1,"mode":1,"type":["SportsCar"]},{"delay":6,"mode":1,"type":["Police"]}]},{"material":"images/stone-block.png"}],"startFrame":4}
